# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               Ranjith Nair - Programming World
tagline:             'Web Developer'
description:         '"Live as if you were to die tomorrow. Learn as if you were to live forever." - Gandhi <br/> Sharing learning through blogs.'
url:                 http:/ranjithnair.github.io
baseurl:

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# About/contact
author:
  name:              Ranjith Nair
  url:               https://twitter.com/ranjith_m
  email:             ranjith2112@gmail.com

# Custom vars
version:             1.0.0
markdown:            kramdown
kramdown:
                     input: GFM
                     syntax_highlighter: rouge
future:              true
plugins :
  - jekyll-paginate-v2
  - jekyll-seo-tag
